apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker1-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: worker1-pv

